apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: sprawdzsluch
spec:
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 38081
  type: NodePort

