apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sprawdzsluch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: localhost:5000/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80   # 🔹 musi się zgadzać z tym co masz w Dockerfile
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:        # 🔹 sprawdzanie zdrowia
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:         # 🔹 sprawdzanie czy nginx żyje
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
