apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-pdf
  namespace: sprawdzsluch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-pdf
  template:
    metadata:
      labels:
        app: backend-pdf
    spec:
      containers:
        - name: backend-pdf
          image: bartoszgwozdz/backend-pdf:latest
          ports:
            - containerPort: 3000

