apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: sprawdzsluch
spec:
  ports:
    - port: 27017
  clusterIP: None   # headless service -> potrzebny dla StatefulSet
  selector:
    app: mongodb

