apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-payments-hpa
  namespace: sprawdzsluch
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-payments
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-pdf-hpa
  namespace: sprawdzsluch
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-pdf
  minReplicas: 1
  maxReplicas: 3  # PDF generation is resource-intensive
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60  # Lower threshold due to CPU-intensive operations
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70  # PDF generation uses lots of memory
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # Longer stabilization for PDF service
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60