apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: observability
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ExternalName
  externalName: grafana.observability.svc.cluster.local
