apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-frontend-prefix
  namespace: sprawdzsluch
spec:
  stripPrefix:
    prefixes:
      - /o-nas
      - /kontakt
      - /test-sluchu
      - /faq
      - /results
      - /polityka-prywatnosci
      - /regulamin
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-mongo-express-prefix
  namespace: sprawdzsluch
spec:
  stripPrefix:
    prefixes:
      - /mongo-express
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-grafana-prefix
  namespace: observability    # zmiana namespace na observability
spec:
  stripPrefix:
    prefixes:
      - /grafana
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sprawdzsluch-frontend
  namespace: sprawdzsluch
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/o-nas`) || PathPrefix(`/kontakt`) || PathPrefix(`/test-sluchu`) || PathPrefix(`/faq`) || PathPrefix(`/results`) || PathPrefix(`/polityka-prywatnosci`) || PathPrefix(`/regulamin`)
      kind: Rule
      services:
        - name: frontend
          port: 80
      middlewares:
        - name: strip-frontend-prefix
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: frontend
          port: 80
      priority: 1
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sprawdzsluch-mongo-express
  namespace: sprawdzsluch
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/mongo-express`)
      kind: Rule
      services:
        - name: mongo-express
          port: 8081
      middlewares:
        - name: strip-mongo-express-prefix
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sprawdzsluch-grafana
  namespace: observability    # zmiana namespace na observability
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/grafana`)
      kind: Rule
      services:
        - name: grafana      # nazwa serwisu Grafany w namespace observability
          port: 3000
      middlewares:
        - name: strip-grafana-prefix
          namespace: observability    # dodanie namespace dla middleware