---
# BACKEND-CORE API
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sprawdzsluch-backend-core
  namespace: sprawdzsluch
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/api`)
      kind: Rule
      services:
        - name: backend-core
          port: 8090
      middlewares:
        - name: add-headers
---
# FRONTEND
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sprawdzsluch-frontend
  namespace: sprawdzsluch
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: frontend
          port: 80
          passHostHeader: true
      middlewares:
        - name: add-headers
---

# MONGO-EXPRESS
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sprawdzsluch-mongo-express
  namespace: sprawdzsluch
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/mongo-express`)
      kind: Rule
      services:
        - name: mongo-express
          port: 8081
      middlewares:
        - name: strip-mongo-express
        - name: add-headers
    - match: PathPrefix(`/public`)
      kind: Rule
      services:
        - name: mongo-express
          port: 8081
      middlewares:
        - name: add-headers
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-mongo-express
  namespace: sprawdzsluch
spec:
  stripPrefix:
    prefixes:
      - /mongo-express
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: add-headers
  namespace: sprawdzsluch
spec:
  headers:
    customRequestHeaders:
      X-Original-URI: "{path}"
      X-Original-Method: "{method}"
    customResponseHeaders:
      X-Served-By: "traefik"