---
# FRONTEND
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sprawdzsluch-frontend
  namespace: sprawdzsluch
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: frontend
          port: 80
---
# MONGO-EXPRESS
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sprawdzsluch-mongo-express
  namespace: sprawdzsluch
spec:
  entryPoints:
    - mongoexpress
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: mongo-express
          port: 8081
---
# GRAFANA
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sprawdzsluch-grafana
  namespace: observability
spec:
  entryPoints:
    - grafana
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: grafana
          port: 3000