apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-ingress
  namespace: sprawdzsluch
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: frontend
          port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mongo-express-ingress
  namespace: sprawdzsluch
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/mongo-express`)
      kind: Rule
      services:
        - name: mongo-express
          port: 8081
      middlewares:
        - name: strip-prefixes

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: sprawdzsluch
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/grafana`)
      kind: Rule
      services:
        - name: grafana-external
          port: 80
      middlewares:
        - name: strip-prefixes

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefixes
  namespace: sprawdzsluch
spec:
  stripPrefix:
    prefixes:
      - /grafana
      - /mongo-express