apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sprawdzsluch-ingress
  namespace: sprawdzsluch
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # Uncomment if you want automatic HTTPS via Let's Encrypt
    # cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  rules:
    - host: sprawdzsluch.pl   # <- wpisz swój domenowy adres
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /pdf
            pathType: Prefix
            backend:
              service:
                name: backend-pdf
                port:
                  number: 3000
          - path: /core
            pathType: Prefix
            backend:
              service:
                name: backend-core
                port:
                  number: 8090
          - path: /mongo-express
            pathType: Prefix
            backend:
              service:
                name: mongo-express
                port:
                  number: 8081
