# --- MIDDLEWARE DLA MONGO-EXPRESS ---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-mongo-express-prefix
  namespace: sprawdzsluch
spec:
  stripPrefix:
    prefixes:
      - /mongo-express
---
# --- MIDDLEWARE DLA GRAFANA ---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-grafana-prefix
  namespace: observability
spec:
  stripPrefix:
    prefixes:
      - /grafana
---
# --- FRONTEND: WSZYSTKIE ŚCIEŻKI ---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sprawdzsluch-frontend
  namespace: sprawdzsluch
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: frontend
          port: 80
      priority: 1
---
# --- MONGO-EXPRESS ---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sprawdzsluch-mongo-express
  namespace: sprawdzsluch
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/mongo-express`)
      kind: Rule
      services:
        - name: mongo-express
          port: 8081
      priority: 100
    - match: PathPrefix(`/mongo-express/static`)
      kind: Rule
      services:
        - name: mongo-express
          port: 8081
      priority: 101
---
# --- GRAFANA ---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sprawdzsluch-grafana
  namespace: observability
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/grafana`)
      kind: Rule
      services:
        - name: grafana
          port: 3000
      middlewares:
        - name: strip-grafana-prefix
          namespace: observability
      priority: 100