apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-grafana-prefix
  namespace: observability
spec:
  stripPrefix:
    prefixes:
      - /grafana
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-mongo-express-prefix
  namespace: sprawdzsluch
spec:
  stripPrefix:
    prefixes:
      - /mongo-express
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sprawdzsluch-ingress-frontend
  namespace: sprawdzsluch
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /o-nas
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /kontakt
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /test-sluchu
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /faq
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /results
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /polityka-prywatnosci
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /regulamin
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sprawdzsluch-ingress-grafana
  namespace: sprawdzsluch
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.middlewares: sprawdzsluch-strip-grafana-prefix@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana-external
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sprawdzsluch-ingress-mongo-express
  namespace: sprawdzsluch
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.middlewares: sprawdzsluch-strip-mongo-express-prefix@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /mongo-express(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: mongo-express
                port:
                  number: 8081