apiVersion: v1
kind: Secret
metadata:
  name: paynow-secret
  namespace: sprawdzsluch
type: Opaque
stringData:
  api-key: replace-with-paynow-api-key
  signature-key: replace-with-paynow-signature-key
