apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-payments
  namespace: sprawdzsluch
  labels:
    app: backend-payments
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-payments
  template:
    metadata:
      labels:
        app: backend-payments
        version: v1
    spec:
      containers:
        - name: backend-payments
          image: localhost:5000/backend-payments:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          
          # Environment variables from ConfigMap
          envFrom:
            - configMapRef:
                name: backend-payments-config
            - secretRef:
                name: backend-payments-secret
          
          # Health checks
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          
          # Resource limits
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          
          # Volume mounts for logs
          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs
      
      # Volumes
      volumes:
        - name: logs-volume
          emptyDir: {}
      
      # Restart policy
      restartPolicy: Always
      
      # DNS policy
      dnsPolicy: ClusterFirst