apiVersion: v1
kind: Service
metadata:
  name: backend-payments-service
  namespace: sprawdzsluch
  labels:
    app: backend-payments
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: backend-payments

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-payments-network-policy
  namespace: sprawdzsluch
spec:
  podSelector:
    matchLabels:
      app: backend-payments
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from backend-core (for payment processing)
    - from:
        - podSelector:
            matchLabels:
              app: backend-core
      ports:
        - protocol: TCP
          port: 8082
    
    # Allow traffic from frontend (for direct payment status checks)
    - from:
        - podSelector:
            matchLabels:
              app: frontend
      ports:
        - protocol: TCP
          port: 8082
    
    # Allow traffic from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: traefik-system
      ports:
        - protocol: TCP
          port: 8082
  
  egress:
    # Allow connection to MongoDB
    - to:
        - podSelector:
            matchLabels:
              app: mongodb
      ports:
        - protocol: TCP
          port: 27017
    
    # Allow connection to Kafka
    - to:
        - podSelector:
            matchLabels:
              app: kafka
      ports:
        - protocol: TCP
          port: 9092
    
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53