deployment:
  enabled: true

ingressRoute:
  dashboard:
    enabled: false

ports:
  web:
    exposedPort: 80
    port: 80
    protocol: TCP
    nodePort: 30080

providers:
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
  kubernetesCRD:
    enabled: true

rbac:
  enabled: true

entryPoints:
  web:
    address: ":80"
