apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-core
  namespace: sprawdzsluch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-core
  template:
    metadata:
      labels:
        app: backend-core
    spec:
      containers:
        - name: backend-core
          image: localhost:5000/backend-core:latest
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: mongodb-uri
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            # MongoDB credentials (jeśli potrzebne)
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password
