name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [deploy]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      K8S_NAMESPACE: sprawdzsluch
      LOCAL_REGISTRY: localhost:5000

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Uruchom lokalny rejestr Docker
      - name: Start local registry
        run: |
          # Zatrzymaj kontener jeśli istnieje
          docker stop registry || true
          # Usuń kontener jeśli istnieje
          docker rm registry || true
          # Usuń powiązane wolumeny
          docker volume rm $(docker volume ls -q -f dangling=true) || true
          # Uruchom nowy kontener rejestru z nazwanymi wolumenami
          docker run -d \
            -p 5000:5000 \
            --name registry \
            -v registry-data:/var/lib/registry \
            registry:2

      # 3️⃣ Build & push frontend locally
      - name: Build & push frontend locally
        run: |
          docker build -t ${LOCAL_REGISTRY}/frontend:latest ./frontend
          docker push ${LOCAL_REGISTRY}/frontend:latest

      # 4️⃣ Build & push backend-pdf locally
      - name: Build & push backend-pdf locally
        run: |
          docker build -t ${LOCAL_REGISTRY}/backend-pdf:latest ./backend-pdf
          docker push ${LOCAL_REGISTRY}/backend-pdf:latest

      # 5️⃣ Build & push backend-core locally
      - name: Build & push backend-core locally
        run: |
          docker build -t ${LOCAL_REGISTRY}/backend-core:latest ./backend-core
          docker push ${LOCAL_REGISTRY}/backend-core:latest

      # 6️⃣ Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.30.0"

      # 7️⃣ Configure kubeconfig
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      # 8️⃣ Create MongoDB Secret
      - name: Create MongoDB Secret
        run: |
          kubectl -n $K8S_NAMESPACE create secret generic mongo-secret \
            --from-literal=mongo-root-username=${{ secrets.MONGO_ROOT_USERNAME }} \
            --from-literal=mongo-root-password=${{ secrets.MONGO_ROOT_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      # 9️⃣ Deploy all manifests
      - name: Deploy all manifests
        run: |
          # Najpierw namespace
          kubectl apply -f k8s/namespace.yaml

          # Następnie secrets i configmapy (jeśli istnieją)
          kubectl apply -f k8s/mongodb/secret.yaml

          # Potem deployment MongoDB
          kubectl apply -f k8s/mongodb/statefulset.yaml
          kubectl apply -f k8s/mongodb/service.yaml

          kubectl apply -f k8s/mongo-express/service.yaml
          kubectl apply -f k8s/mongo-express/deployment.yaml

          # Na końcu aplikacje
          kubectl apply -f k8s/frontend/deployment.yaml
          kubectl apply -f k8s/frontend/service.yaml
          kubectl apply -f k8s/backend-core/deployment.yaml
          kubectl apply -f k8s/backend-core/service.yaml
          kubectl apply -f k8s/backend-pdf/deployment.yaml
          kubectl apply -f k8s/backend-pdf/service.yaml

          # Na samym końcu ingress
          # kubectl apply -f k8s/ingress.yaml

          kubectl rollout status statefulset/mongodb -n $K8S_NAMESPACE
          kubectl rollout status deployment/frontend -n $K8S_NAMESPACE
          kubectl rollout status deployment/backend-pdf -n $K8S_NAMESPACE
          kubectl rollout status deployment/backend-core -n $K8S_NAMESPACE

      # 🧹 Cleanup
      - name: Cleanup
        if: always()
        run: |
          docker stop registry || true
          docker rm registry || true
          docker volume rm registry-data || true
          docker system prune -f --volumes
